<?php

/**
 * This file contains framework settings and configurations.
 */

/*
*------------------------------------------------------------------------------
* Development environment
*------------------------------------------------------------------------------
*
* If you're in a development environment, turn on direct error reporting by
* setting the following to `true`. If you're in a production environment,
* turn off direct error reporting by setting the constant below to `false`
* and let errors be logged to the error log file.
*
*/

define ("DEVELOPMENT_ENVIRONMENT", true);

/*
*------------------------------------------------------------------------------
* Once a cheater, always a cheater
*------------------------------------------------------------------------------
*
* Use these mnemonics to shorten long names.
*
*/

define ("DS", DIRECTORY_SEPARATOR);
define ("SLASH", DIRECTORY_SEPARATOR);

/*
*------------------------------------------------------------------------------
* Setup global directory paths
*------------------------------------------------------------------------------
*
*  ...
*
*/

// App directory - this directory stores the application code.
define ("APP_DIRECTORY", ENVIRONMENT_PATH . DS . "app");

// Bootstrap directory - this directory stores the files that bootstrap the framework.
define ("BOOTSTRAP_DIRECTORY", ENVIRONMENT_PATH . DS . "bootstrap");

// Config directory - this directory stores application configurations.
define ("CONFIG_DIRECTORY", ENVIRONMENT_PATH . DS . "config");

// Core directory - this directory stores the framework core.
define ("CORE_DIRECTORY", ENVIRONMENT_PATH . DS . "core");

// Resources directory - this directory stores the framework resources.
define ("RESOURCE_DIRECTORY", ENVIRONMENT_PATH . SLASH . "resources");
define ("TEMPLATE_DIRECTORY", RESOURCE_DIRECTORY . SLASH . "templates");

// Storage directory - this directory is a storage for files generated by
// the application, framework, and Composer dependencies.
define ("STORAGE_DIRECTORY", ENVIRONMENT_PATH . DS . "storage");
define ("APP_STORAGE_DIRECTORY", STORAGE_DIRECTORY . DS . "app");
define ("FRAMEWORK_STORAGE_DIRECTORY", STORAGE_DIRECTORY . DS . "framework");
define ("FRAMEWORK_CACHE_DIRECTORY", FRAMEWORK_STORAGE_DIRECTORY . DS . "cache");
define ("LOGS_STORAGE_DIRECTORY", STORAGE_DIRECTORY . DS . "logs");
define ("VENDOR_STORAGE_DIRECTORY", STORAGE_DIRECTORY . DS . "vendor");

// Public directory - this directory stores files like the front-controller,
// and website assets like CSS, images, and javascript.
define ("PUBLIC_DIRECTORY", ENVIRONMENT_PATH . DS . "public");

// Vendor directory - this directory stores Composer dependencies.
define ("VENDOR_DIRECTORY", ENVIRONMENT_PATH . DS . "vendor");

/*
*-------------------------------------------------------------------------------
* Let Octagon what path to save Twig's compilation cache
*-------------------------------------------------------------------------------
*
* ...
*
*/

define ("TWIG_STORAGE_DIRECTORY", VENDOR_STORAGE_DIRECTORY . DS . "twig");
define ("TWIG_COMPILATION_CACHE_DIRECTORY", TWIG_STORAGE_DIRECTORY . DS . "compilation_cache");

/*
*------------------------------------------------------------------------------
* Set the default file extension used by all framework and application files.
*------------------------------------------------------------------------------
*
* Geometry uses a single file extension for all framework and application files.
*
*/

define ("FILE_EXTENSION", ".php");

/*
*------------------------------------------------------------------------------
* Set the name of the app config file
*------------------------------------------------------------------------------
*
* ...
*
*/

define ("CONFIG_FILE", "config".FILE_EXTENSION);

/*
*------------------------------------------------------------------------------
* Set the name of the app config file
*------------------------------------------------------------------------------
*
* ...
*
*/

define ("APP_ROUTE_FILE", "routes".FILE_EXTENSION);

/*
*------------------------------------------------------------------------------
* Set the name of the framework's error log file.
*------------------------------------------------------------------------------
*
* Geometry avoids sending out internal error messages back to the client
* because, frankly, it's none of his business. Geometry instead logs internal
* errors to a log file, so that you can know what went wrong inside the
* framework. Provide the filename you'd prefer below.
*
*/

define ("ERROR_LOG_FILE", "error.log");

/*
*------------------------------------------------------------------------------
* Set the name of the application's debug log file.
*------------------------------------------------------------------------------
*
* ...
*
*/

define ("DEBUG_LOG_FILE", "debug.log");
